name: Create CV zip file with HTML, DOC and PDF outputs

on:
  workflow_dispatch:
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3 # this checks out the repo in the ubuntu container
      - name: "Create a folder called output"
        run: |
          mkdir output
          cp cv-stylesheet.css output/cv-stylesheet.css

      # Downloading the binaries directly (current as of 14/07/2023) because they are newer and work better, than the ones that come with Ubuntu latest.
      - name: "Install pandoc and wkhtmltopdf"
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.1.5/pandoc-3.1.5-1-amd64.deb         
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.jammy_amd64.deb
        
          sudo apt install ./pandoc-3.1.5-1-amd64.deb
          sudo apt install ./wkhtmltox_0.12.6.1-3.jammy_amd64.deb

      - name: "Convert MD to HTML"
        run: |
          pandoc -s $(cat includes.txt) -f markdown -t html -c cv-stylesheet.css -o output/${{github.actor}}-cv.html
          cp output/${{github.actor}}-cv.html output/index.html

      - name: "Convert MD to DOC"
        run: |        
          pandoc -s $(cat includes.txt) -f markdown -t docx -c cv-stylesheet.css -o output/${{github.actor}}-cv.doc

      - name: "Convert HTML to PDF "
        run: "wkhtmltopdf --enable-local-file-access output/${{github.actor}}-cv.html output/${{github.actor}}-cv.pdf" 
      # run: |
      #     /usr/bin/pandoc -standalone cat includes.txt --output=output/cv.pdf --css=cv-stylesheet.css --from=markdown --to=pdf --pdf-engine=/usr/bin/wkhtmltopdf

      - uses: actions/upload-artifact@master
        with: # basically this will put cv.html, cv.doc and cv.pdf in a zip file.
          name: ${{ github.actor }}-cv
          path: output

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./output/index.html
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: convert_via_pandoc
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
